### ISSUE TITLE
10Gbs connection upgrade for P1 and P2

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/sysmaintenance#10]

**Comment by ghost** [comment]
root@penguin:/home# lshw -C network
  *-network DISABLED
       description: Ethernet interface
       product: 82574L Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:05:00.0
       logical name: eth0
       version: 00
       serial: 08:60:6e:1c:bf:0c
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=2.3.2-k firmware=2.1-3 latency=0 link=no multicast=yes port=twisted pair
       resources: irq:16 memory:cfb00000-cfb1ffff ioport:6000(size=32) memory:cfb20000-cfb23fff
  *-network
       description: Ethernet interface
       product: 82574L Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:06:00.0
       logical name: eth1
       version: 00
       serial: 08:60:6e:1c:bf:0d
       size: 100Mbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=2.3.2-k duplex=full firmware=2.1-3 ip=128.169.4.95 latency=0 link=yes multicast=yes port=twisted pair speed=100Mbit/s
       resources: irq:17 memory:cfa00000-cfa1ffff ioport:5000(size=32) memory:cfa20000-cfa23fff

**Comment by ghost** [comment]
root@penguin2:~# lshw -C network
  *-network
       description: Ethernet interface
       product: I210 Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:05:00.0
       logical name: eth0
       version: 03
       serial: 1c:b7:2c:05:90:ef
       size: 100Mbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.2.15-k duplex=full firmware=3.16, 0x800004d7 ip=128.169.4.44 latency=0 link=yes multicast=yes port=twisted pair speed=100Mbit/s
       resources: irq:16 memory:c6200000-c627ffff ioport:6000(size=32) memory:c6280000-c6283fff
  *-network
       description: Ethernet interface
       product: I210 Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:06:00.0
       logical name: eth1
       version: 03
       serial: 1c:b7:2c:05:90:f0
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.2.15-k firmware=3.16, 0x80000513 latency=0 link=no multicast=yes port=twisted pair
       resources: irq:17 memory:c6100000-c617ffff ioport:5000(size=32) memory:c6180000-c6183fff

**Comment by ghost** [comment]
Your case with Penguin Computing has been updated.
Bikram Singh Posted the following:

Hello Lei,

Thank you for contacting Penguin Computing. I will forward your request to
our sales team and someone will be in touch with you shortly.

FYI...

P1725299 is out of warranty as of 6/12/2016.

Regards,
Bikram

---

_Case_: 00082752
_Status_: Open
_Priority Level_:
_Subject_: [Support] upgrade to 10Gbs copper NICs
_Description_:
Hi,

Our research center has two Penguin Relion 2800GT servers, and their serial
numbers are P1725299 and P100115281.

Now we want to upgrade the NICs to 10Gbs copper NICs. So could you please
let us know which models we can use, and where we can buy from? Thanks a
lot.

Lei Yan
IT Administrator IV
Center for Integrative and Translational Genomics
The University of Tennessee Health Science Center

**Comment by pjotrp** [comment]
Any news here?

**Comment by robwwilliams** [comment]
I'm with Lei April 3, 2017,  trying to decide the NIC we need for Penguin. We have an Intel 1 Gbps NIC (82574L) in Penguin now. This is an Ethernet card.

https://ark.intel.com/products/32209/Intel-82574L-Gigabit-Ethernet-Controller

Is this what we want?  Intel X520-SR1 (with 10 Gbps fiber) PCIe2 board: cost is $599.77 at NewEgg

http://www.intel.com/content/www/us/en/ethernet-products/converged-network-adapters/ethernet-x520.html

**Comment by pjotrp** [comment]
Access between servers is currently at 10Mbs - even within the data center.

**Comment by ghost** [comment]
I got the Intel Server Adapter X520-SR1. So now I will install it on P1 or P2 first, and this need about one hour, and that means the server will stop running for one hour. So which server is Ok for testing? And what’s the good time?

**Comment by pjotrp** [comment]
P2 runs nothing critical. Go ahead.

**Comment by pjotrp** [comment]
Great speed improvement. Shame about the HDD crash.
