### ISSUE TITLE
Faster connection between P1 and P2

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/sysmaintenance#16]
The connection between the machines is *slow*. Probably an idea to look at Lily too.

**Comment by ghost** [comment]
I tested the speed (using rsync):

P1 <-> P2
11.19MB/s

P1 <-> Lily
11.13MB/s

Lily <-> P2
11.20MB/s

The speed is very stable, but maybe slow. I will report this to IT department.

**Comment by ghost** [comment]
Changed switch this afternoon, and I tested the speed (using rsync):

P1 <-> Lily
50.13MB/s

**Comment by pjotrp** [comment]
Nice.
