### ISSUE TITLE
Monitoring software

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/sysmaintenance#9]
What monitoring software are we using to see if 
1. The webservers are up and running
2. The http daemon is responding (main page is enough)
3. To test the performance of requests (one search is enough)

Ideally the monitoring should be done from outside the UTHSC network.

**Comment by ghost** [comment]
I will use this service:

http://uptimerobot.com/

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10780099/19902913/90726fa2-a03a-11e6-98c9-5b010e35f780.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10780099/19902945/b75108ea-a03a-11e6-8ec9-c08591d319cf.png)

**Comment by pjotrp** [comment]
Cool. Can we monitor some more servers?

**Comment by pjotrp** [comment]
These are services used by different people:

http://gn2.genenetwork.org/
http://test-gn2.genenetwork.org/
http://files.genenetwork.org/
http://guix.genenetwork.org:8080/

And add one of my E-mail addresses to the notifier.

**Comment by lyan6** [comment]
@pjotrp 
Hi Pjotrp,


I have sent you an invitation, you are (pjotr2016@thebird.nl) just added as an "e-mail alert contact" to the Uptime Robot account. Please activate it in your email.


For this service, the monitor system got a "Not Found (404)" response, so can you give me a "OK (200)" response URL?
http://guix.genenetwork.org:8080/

**Comment by ghost** [comment]
@pjotrp 
Hi Pjotrp,

For this service, the monitor system got a "Not Found (404)" response, so can you give me a "OK (200)" response URL?
http://guix.genenetwork.org:8080/

**Comment by pjotrp** [comment]
http://guix.genenetwork.org:8080/nix-cache-info

**Comment by ghost** [comment]
have set up

![image](https://cloud.githubusercontent.com/assets/10780099/19949968/b29fb48e-a122-11e6-80ac-6ca3a3b73f04.png)
